name: riverpod_change_notifier_provider
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.2

isar_version: &isar_version 3.1.0+1

dependencies:
  path_provider:
  isar: *isar_version
  isar_flutter_libs: *isar_version
  provider: any
  flutter_svg: ^2.0.6
  intl: any
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

dev_dependencies:
  isar_generator: *isar_version
  build_runner: any
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

